use crate::stacks::{Stack, StackFile};

pub fn react_vite() -> Stack {
    Stack {
        name: "react-vite".into(),
        runtime: "bun".into(),
        description: "React 19 + Vite 8 + Tailwind 4 + Zustand + TanStack Query + React Router 7 (Complete Modern Template)".into(),
                packages: vec![
            "@babel/code-frame".into(),
            "@babel/compat-data".into(),
            "@babel/core".into(),
            "@babel/generator".into(),
            "@babel/helper-compilation-targets".into(),
            "@babel/helper-globals".into(),
            "@babel/helper-module-imports".into(),
            "@babel/helper-module-transforms".into(),
            "@babel/helper-string-parser".into(),
            "@babel/helper-validator-identifier".into(),
            "@babel/helper-validator-option".into(),
            "@babel/helpers".into(),
            "@babel/parser".into(),
            "@babel/template".into(),
            "@babel/traverse".into(),
            "@babel/types".into(),
            "@eslint-community/eslint-utils".into(),
            "@eslint-community/regexpp".into(),
            "@eslint/config-array".into(),
            "@eslint/config-helpers".into(),
            "@eslint/core".into(),
            "@eslint/eslintrc".into(),
            "@eslint/js".into(),
            "@eslint/object-schema".into(),
            "@eslint/plugin-kit".into(),
            "@hookform/resolvers".into(),
            "@humanfs/core".into(),
            "@humanfs/node".into(),
            "@humanwhocodes/module-importer".into(),
            "@humanwhocodes/retry".into(),
            "@jridgewell/gen-mapping".into(),
            "@jridgewell/remapping".into(),
            "@jridgewell/resolve-uri".into(),
            "@jridgewell/sourcemap-codec".into(),
            "@jridgewell/trace-mapping".into(),
            "@oxc-project/types".into(),
            "@rolldown/binding-linux-x64-gnu".into(),
            "@rolldown/binding-linux-x64-musl".into(),
            "@rolldown/pluginutils".into(),
            "@standard-schema/utils".into(),
            "@tailwindcss/node".into(),
            "@tailwindcss/oxide".into(),
            "@tailwindcss/oxide-linux-x64-gnu".into(),
            "@tailwindcss/oxide-linux-x64-musl".into(),
            "@tailwindcss/vite".into(),
            "@tanstack/query-core".into(),
            "@tanstack/react-query".into(),
            "@types/estree".into(),
            "@types/json-schema".into(),
            "@types/node".into(),
            "@types/react".into(),
            "@types/react-dom".into(),
            "@typescript-eslint/eslint-plugin".into(),
            "@typescript-eslint/parser".into(),
            "@typescript-eslint/project-service".into(),
            "@typescript-eslint/scope-manager".into(),
            "@typescript-eslint/tsconfig-utils".into(),
            "@typescript-eslint/type-utils".into(),
            "@typescript-eslint/types".into(),
            "@typescript-eslint/typescript-estree".into(),
            "@typescript-eslint/utils".into(),
            "@typescript-eslint/visitor-keys".into(),
            "@vitejs/plugin-react".into(),
            "acorn".into(),
            "acorn-jsx".into(),
            "ajv".into(),
            "ansi-styles".into(),
            "argparse".into(),
            "asynckit".into(),
            "axios".into(),
            "balanced-match".into(),
            "baseline-browser-mapping".into(),
            "brace-expansion".into(),
            "browserslist".into(),
            "call-bind-apply-helpers".into(),
            "callsites".into(),
            "caniuse-lite".into(),
            "chalk".into(),
            "color-convert".into(),
            "color-name".into(),
            "combined-stream".into(),
            "concat-map".into(),
            "convert-source-map".into(),
            "cookie".into(),
            "cross-spawn".into(),
            "csstype".into(),
            "debug".into(),
            "deep-is".into(),
            "delayed-stream".into(),
            "detect-libc".into(),
            "dunder-proto".into(),
            "electron-to-chromium".into(),
            "enhanced-resolve".into(),
            "es-define-property".into(),
            "es-errors".into(),
            "es-object-atoms".into(),
            "es-set-tostringtag".into(),
            "escalade".into(),
            "escape-string-regexp".into(),
            "eslint".into(),
            "eslint-plugin-react-hooks".into(),
            "eslint-plugin-react-refresh".into(),
            "eslint-scope".into(),
            "eslint-visitor-keys".into(),
            "espree".into(),
            "esquery".into(),
            "esrecurse".into(),
            "estraverse".into(),
            "esutils".into(),
            "fast-deep-equal".into(),
            "fast-json-stable-stringify".into(),
            "fast-levenshtein".into(),
            "fdir".into(),
            "file-entry-cache".into(),
            "find-up".into(),
            "flat-cache".into(),
            "flatted".into(),
            "follow-redirects".into(),
            "form-data".into(),
            "function-bind".into(),
            "gensync".into(),
            "get-intrinsic".into(),
            "get-proto".into(),
            "glob-parent".into(),
            "globals".into(),
            "gopd".into(),
            "graceful-fs".into(),
            "has-flag".into(),
            "has-symbols".into(),
            "has-tostringtag".into(),
            "hasown".into(),
            "hermes-estree".into(),
            "hermes-parser".into(),
            "ignore".into(),
            "import-fresh".into(),
            "imurmurhash".into(),
            "is-extglob".into(),
            "is-glob".into(),
            "isexe".into(),
            "jiti".into(),
            "js-tokens".into(),
            "js-yaml".into(),
            "jsesc".into(),
            "json-buffer".into(),
            "json-schema-traverse".into(),
            "json-stable-stringify-without-jsonify".into(),
            "json5".into(),
            "keyv".into(),
            "levn".into(),
            "lightningcss".into(),
            "lightningcss-linux-x64-gnu".into(),
            "lightningcss-linux-x64-musl".into(),
            "locate-path".into(),
            "lodash.merge".into(),
            "lru-cache".into(),
            "lucide-react".into(),
            "magic-string".into(),
            "math-intrinsics".into(),
            "mime-db".into(),
            "mime-types".into(),
            "minimatch".into(),
            "ms".into(),
            "nanoid".into(),
            "natural-compare".into(),
            "node-releases".into(),
            "optionator".into(),
            "p-limit".into(),
            "p-locate".into(),
            "parent-module".into(),
            "path-exists".into(),
            "path-key".into(),
            "picocolors".into(),
            "picomatch".into(),
            "postcss".into(),
            "prelude-ls".into(),
            "proxy-from-env".into(),
            "punycode".into(),
            "react".into(),
            "react-dom".into(),
            "react-hook-form".into(),
            "react-router".into(),
            "react-router-dom".into(),
            "resolve-from".into(),
            "rolldown".into(),
            "scheduler".into(),
            "semver".into(),
            "set-cookie-parser".into(),
            "shebang-command".into(),
            "shebang-regex".into(),
            "source-map-js".into(),
            "strip-json-comments".into(),
            "supports-color".into(),
            "tailwindcss".into(),
            "tapable".into(),
            "tinyglobby".into(),
            "ts-api-utils".into(),
            "type-check".into(),
            "typescript".into(),
            "typescript-eslint".into(),
            "undici-types".into(),
            "update-browserslist-db".into(),
            "uri-js".into(),
            "vite".into(),
            "which".into(),
            "word-wrap".into(),
            "yallist".into(),
            "yocto-queue".into(),
            "zod".into(),
            "zod-validation-error".into(),
            "zustand".into(),
        ],
        dev_packages: vec![
            "vite".into(),
            "@vitejs/plugin-react".into(),
            "typescript".into(),
            "@types/react".into(),
            "@types/react-dom".into(),
            "@types/node".into(),
            "eslint".into(),
            "@eslint/js".into(),
            "eslint-plugin-react-hooks".into(),
            "eslint-plugin-react-refresh".into(),
            "globals".into(),
            "typescript-eslint".into(),
            "rolldown".into(),
        ],
        files: vec![
            StackFile {
                path: "README.md".into(),
                content: include_str!("../../../../sample_web/README.md").into(),
                binary_content: None,
            },
            StackFile {
                path: "package.json".into(),
                content: include_str!("../../../../sample_web/package.json").into(),
                binary_content: None,
            },
            StackFile {
                path: "package-lock.json".into(),
                content: include_str!("../../../../sample_web/package-lock.json").into(),
                binary_content: None,
            },
            StackFile {
                path: "bun.lock".into(),
                content: include_str!("../../../../sample_web/bun.lock").into(),
                binary_content: None,
            },
            StackFile {
                path: "tsconfig.json".into(),
                content: include_str!("../../../../sample_web/tsconfig.json").into(),
                binary_content: None,
            },
            StackFile {
                path: "tsconfig.app.json".into(),
                content: include_str!("../../../../sample_web/tsconfig.app.json").into(),
                binary_content: None,
            },
            StackFile {
                path: "tsconfig.node.json".into(),
                content: include_str!("../../../../sample_web/tsconfig.node.json").into(),
                binary_content: None,
            },
            StackFile {
                path: "vite.config.ts".into(),
                content: include_str!("../../../../sample_web/vite.config.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "eslint.config.js".into(),
                content: include_str!("../../../../sample_web/eslint.config.js").into(),
                binary_content: None,
            },
            StackFile {
                path: "index.html".into(),
                content: include_str!("../../../../sample_web/index.html").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/main.tsx".into(),
                content: include_str!("../../../../sample_web/src/main.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/App.tsx".into(),
                content: include_str!("../../../../sample_web/src/App.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/App.css".into(),
                content: include_str!("../../../../sample_web/src/App.css").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/index.css".into(),
                content: include_str!("../../../../sample_web/src/index.css").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/api/axios.ts".into(),
                content: include_str!("../../../../sample_web/src/api/axios.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/assets/react.svg".into(),
                content: include_str!("../../../../sample_web/src/assets/react.svg").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/assets/vite.svg".into(),
                content: include_str!("../../../../sample_web/src/assets/vite.svg").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/assets/hero.png".into(),
                content: "".into(),
                binary_content: Some(include_bytes!("assets/hero.png").to_vec()),
            },
            StackFile {
                path: "src/components/Navbar.tsx".into(),
                content: include_str!("../../../../sample_web/src/components/Navbar.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/components/ThemeProvider.tsx".into(),
                content: include_str!("../../../../sample_web/src/components/ThemeProvider.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/components/ThemeToggleButton.tsx".into(),
                content: include_str!("../../../../sample_web/src/components/ThemeToggleButton.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/components/button.tsx".into(),
                content: include_str!("../../../../sample_web/src/components/button.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/hooks/useUser.ts".into(),
                content: include_str!("../../../../sample_web/src/hooks/useUser.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/layouts/RootLayout.tsx".into(),
                content: include_str!("../../../../sample_web/src/layouts/RootLayout.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/lib/logger.ts".into(),
                content: include_str!("../../../../sample_web/src/lib/logger.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/pages/HomePage.tsx".into(),
                content: include_str!("../../../../sample_web/src/pages/HomePage.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/pages/NotFoundPage.tsx".into(),
                content: include_str!("../../../../sample_web/src/pages/NotFoundPage.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/providers/QueryProvider.tsx".into(),
                content: include_str!("../../../../sample_web/src/providers/QueryProvider.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/store/useAppStore.ts".into(),
                content: include_str!("../../../../sample_web/src/store/useAppStore.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/store/useThemeStore.ts".into(),
                content: include_str!("../../../../sample_web/src/store/useThemeStore.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/types/schema.ts".into(),
                content: include_str!("../../../../sample_web/src/types/schema.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "public/favicon.svg".into(),
                content: include_str!("../../../../sample_web/public/favicon.svg").into(),
                binary_content: None,
            },
            StackFile {
                path: "public/icons.svg".into(),
                content: include_str!("../../../../sample_web/public/icons.svg").into(),
                binary_content: None,
            },
            StackFile {
                path: ".gitignore".into(),
                content: include_str!("../../../../sample_web/.gitignore").into(),
                binary_content: None,
            },
        ],
    }
}




pub fn react_vite_full() -> Stack {
    Stack {
        name: "react-vite-full".into(),
        runtime: "bun".into(),
        description: "React 19 + Vite 8 + Tailwind 4 + Zustand + TanStack Query + React Router 7 (Complete Modern Template)".into(),
                packages: vec![
            "@babel/code-frame".into(),
            "@babel/compat-data".into(),
            "@babel/core".into(),
            "@babel/generator".into(),
            "@babel/helper-compilation-targets".into(),
            "@babel/helper-globals".into(),
            "@babel/helper-module-imports".into(),
            "@babel/helper-module-transforms".into(),
            "@babel/helper-string-parser".into(),
            "@babel/helper-validator-identifier".into(),
            "@babel/helper-validator-option".into(),
            "@babel/helpers".into(),
            "@babel/parser".into(),
            "@babel/template".into(),
            "@babel/traverse".into(),
            "@babel/types".into(),
            "@eslint-community/eslint-utils".into(),
            "@eslint-community/regexpp".into(),
            "@eslint/config-array".into(),
            "@eslint/config-helpers".into(),
            "@eslint/core".into(),
            "@eslint/eslintrc".into(),
            "@eslint/js".into(),
            "@eslint/object-schema".into(),
            "@eslint/plugin-kit".into(),
            "@hookform/resolvers".into(),
            "@humanfs/core".into(),
            "@humanfs/node".into(),
            "@humanwhocodes/module-importer".into(),
            "@humanwhocodes/retry".into(),
            "@jridgewell/gen-mapping".into(),
            "@jridgewell/remapping".into(),
            "@jridgewell/resolve-uri".into(),
            "@jridgewell/sourcemap-codec".into(),
            "@jridgewell/trace-mapping".into(),
            "@oxc-project/types".into(),
            "@rolldown/binding-linux-x64-gnu".into(),
            "@rolldown/binding-linux-x64-musl".into(),
            "@rolldown/pluginutils".into(),
            "@standard-schema/utils".into(),
            "@tailwindcss/node".into(),
            "@tailwindcss/oxide".into(),
            "@tailwindcss/oxide-linux-x64-gnu".into(),
            "@tailwindcss/oxide-linux-x64-musl".into(),
            "@tailwindcss/vite".into(),
            "@tanstack/query-core".into(),
            "@tanstack/react-query".into(),
            "@types/estree".into(),
            "@types/json-schema".into(),
            "@types/node".into(),
            "@types/react".into(),
            "@types/react-dom".into(),
            "@typescript-eslint/eslint-plugin".into(),
            "@typescript-eslint/parser".into(),
            "@typescript-eslint/project-service".into(),
            "@typescript-eslint/scope-manager".into(),
            "@typescript-eslint/tsconfig-utils".into(),
            "@typescript-eslint/type-utils".into(),
            "@typescript-eslint/types".into(),
            "@typescript-eslint/typescript-estree".into(),
            "@typescript-eslint/utils".into(),
            "@typescript-eslint/visitor-keys".into(),
            "@vitejs/plugin-react".into(),
            "acorn".into(),
            "acorn-jsx".into(),
            "ajv".into(),
            "ansi-styles".into(),
            "argparse".into(),
            "asynckit".into(),
            "axios".into(),
            "balanced-match".into(),
            "baseline-browser-mapping".into(),
            "brace-expansion".into(),
            "browserslist".into(),
            "call-bind-apply-helpers".into(),
            "callsites".into(),
            "caniuse-lite".into(),
            "chalk".into(),
            "color-convert".into(),
            "color-name".into(),
            "combined-stream".into(),
            "concat-map".into(),
            "convert-source-map".into(),
            "cookie".into(),
            "cross-spawn".into(),
            "csstype".into(),
            "debug".into(),
            "deep-is".into(),
            "delayed-stream".into(),
            "detect-libc".into(),
            "dunder-proto".into(),
            "electron-to-chromium".into(),
            "enhanced-resolve".into(),
            "es-define-property".into(),
            "es-errors".into(),
            "es-object-atoms".into(),
            "es-set-tostringtag".into(),
            "escalade".into(),
            "escape-string-regexp".into(),
            "eslint".into(),
            "eslint-plugin-react-hooks".into(),
            "eslint-plugin-react-refresh".into(),
            "eslint-scope".into(),
            "eslint-visitor-keys".into(),
            "espree".into(),
            "esquery".into(),
            "esrecurse".into(),
            "estraverse".into(),
            "esutils".into(),
            "fast-deep-equal".into(),
            "fast-json-stable-stringify".into(),
            "fast-levenshtein".into(),
            "fdir".into(),
            "file-entry-cache".into(),
            "find-up".into(),
            "flat-cache".into(),
            "flatted".into(),
            "follow-redirects".into(),
            "form-data".into(),
            "function-bind".into(),
            "gensync".into(),
            "get-intrinsic".into(),
            "get-proto".into(),
            "glob-parent".into(),
            "globals".into(),
            "gopd".into(),
            "graceful-fs".into(),
            "has-flag".into(),
            "has-symbols".into(),
            "has-tostringtag".into(),
            "hasown".into(),
            "hermes-estree".into(),
            "hermes-parser".into(),
            "ignore".into(),
            "import-fresh".into(),
            "imurmurhash".into(),
            "is-extglob".into(),
            "is-glob".into(),
            "isexe".into(),
            "jiti".into(),
            "js-tokens".into(),
            "js-yaml".into(),
            "jsesc".into(),
            "json-buffer".into(),
            "json-schema-traverse".into(),
            "json-stable-stringify-without-jsonify".into(),
            "json5".into(),
            "keyv".into(),
            "levn".into(),
            "lightningcss".into(),
            "lightningcss-linux-x64-gnu".into(),
            "lightningcss-linux-x64-musl".into(),
            "locate-path".into(),
            "lodash.merge".into(),
            "lru-cache".into(),
            "lucide-react".into(),
            "magic-string".into(),
            "math-intrinsics".into(),
            "mime-db".into(),
            "mime-types".into(),
            "minimatch".into(),
            "ms".into(),
            "nanoid".into(),
            "natural-compare".into(),
            "node-releases".into(),
            "optionator".into(),
            "p-limit".into(),
            "p-locate".into(),
            "parent-module".into(),
            "path-exists".into(),
            "path-key".into(),
            "picocolors".into(),
            "picomatch".into(),
            "postcss".into(),
            "prelude-ls".into(),
            "proxy-from-env".into(),
            "punycode".into(),
            "react".into(),
            "react-dom".into(),
            "react-hook-form".into(),
            "react-router".into(),
            "react-router-dom".into(),
            "resolve-from".into(),
            "rolldown".into(),
            "scheduler".into(),
            "semver".into(),
            "set-cookie-parser".into(),
            "shebang-command".into(),
            "shebang-regex".into(),
            "source-map-js".into(),
            "strip-json-comments".into(),
            "supports-color".into(),
            "tailwindcss".into(),
            "tapable".into(),
            "tinyglobby".into(),
            "ts-api-utils".into(),
            "type-check".into(),
            "typescript".into(),
            "typescript-eslint".into(),
            "undici-types".into(),
            "update-browserslist-db".into(),
            "uri-js".into(),
            "vite".into(),
            "which".into(),
            "word-wrap".into(),
            "yallist".into(),
            "yocto-queue".into(),
            "zod".into(),
            "zod-validation-error".into(),
            "zustand".into(),
        ],
        dev_packages: vec![
            "vite".into(),
            "@vitejs/plugin-react".into(),
            "typescript".into(),
            "@types/react".into(),
            "@types/react-dom".into(),
            "@types/node".into(),
            "eslint".into(),
            "@eslint/js".into(),
            "eslint-plugin-react-hooks".into(),
            "eslint-plugin-react-refresh".into(),
            "globals".into(),
            "typescript-eslint".into(),
            "rolldown".into(),
        ],
        files: vec![
            StackFile {
                path: "README.md".into(),
                content: include_str!("../../../../sample_web/README.md").into(),
                binary_content: None,
            },
            StackFile {
                path: "package.json".into(),
                content: include_str!("../../../../sample_web/package.json").into(),
                binary_content: None,
            },
            StackFile {
                path: "package-lock.json".into(),
                content: include_str!("../../../../sample_web/package-lock.json").into(),
                binary_content: None,
            },
            StackFile {
                path: "bun.lock".into(),
                content: include_str!("../../../../sample_web/bun.lock").into(),
                binary_content: None,
            },
            StackFile {
                path: "tsconfig.json".into(),
                content: include_str!("../../../../sample_web/tsconfig.json").into(),
                binary_content: None,
            },
            StackFile {
                path: "tsconfig.app.json".into(),
                content: include_str!("../../../../sample_web/tsconfig.app.json").into(),
                binary_content: None,
            },
            StackFile {
                path: "tsconfig.node.json".into(),
                content: include_str!("../../../../sample_web/tsconfig.node.json").into(),
                binary_content: None,
            },
            StackFile {
                path: "vite.config.ts".into(),
                content: include_str!("../../../../sample_web/vite.config.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "eslint.config.js".into(),
                content: include_str!("../../../../sample_web/eslint.config.js").into(),
                binary_content: None,
            },
            StackFile {
                path: "index.html".into(),
                content: include_str!("../../../../sample_web/index.html").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/main.tsx".into(),
                content: include_str!("../../../../sample_web/src/main.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/App.tsx".into(),
                content: include_str!("../../../../sample_web/src/App.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/App.css".into(),
                content: include_str!("../../../../sample_web/src/App.css").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/index.css".into(),
                content: include_str!("../../../../sample_web/src/index.css").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/api/axios.ts".into(),
                content: include_str!("../../../../sample_web/src/api/axios.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/assets/react.svg".into(),
                content: include_str!("../../../../sample_web/src/assets/react.svg").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/assets/vite.svg".into(),
                content: include_str!("../../../../sample_web/src/assets/vite.svg").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/assets/hero.png".into(),
                content: "".into(),
                binary_content: Some(include_bytes!("assets/hero.png").to_vec()),
            },
            StackFile {
                path: "src/components/Navbar.tsx".into(),
                content: include_str!("../../../../sample_web/src/components/Navbar.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/components/ThemeProvider.tsx".into(),
                content: include_str!("../../../../sample_web/src/components/ThemeProvider.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/components/ThemeToggleButton.tsx".into(),
                content: include_str!("../../../../sample_web/src/components/ThemeToggleButton.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/components/button.tsx".into(),
                content: include_str!("../../../../sample_web/src/components/button.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/hooks/useUser.ts".into(),
                content: include_str!("../../../../sample_web/src/hooks/useUser.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/layouts/RootLayout.tsx".into(),
                content: include_str!("../../../../sample_web/src/layouts/RootLayout.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/lib/logger.ts".into(),
                content: include_str!("../../../../sample_web/src/lib/logger.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/pages/HomePage.tsx".into(),
                content: include_str!("../../../../sample_web/src/pages/HomePage.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/pages/NotFoundPage.tsx".into(),
                content: include_str!("../../../../sample_web/src/pages/NotFoundPage.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/providers/QueryProvider.tsx".into(),
                content: include_str!("../../../../sample_web/src/providers/QueryProvider.tsx").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/store/useAppStore.ts".into(),
                content: include_str!("../../../../sample_web/src/store/useAppStore.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/store/useThemeStore.ts".into(),
                content: include_str!("../../../../sample_web/src/store/useThemeStore.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "src/types/schema.ts".into(),
                content: include_str!("../../../../sample_web/src/types/schema.ts").into(),
                binary_content: None,
            },
            StackFile {
                path: "public/favicon.svg".into(),
                content: include_str!("../../../../sample_web/public/favicon.svg").into(),
                binary_content: None,
            },
            StackFile {
                path: "public/icons.svg".into(),
                content: include_str!("../../../../sample_web/public/icons.svg").into(),
                binary_content: None,
            },
            StackFile {
                path: ".gitignore".into(),
                content: include_str!("../../../../sample_web/.gitignore").into(),
                binary_content: None,
            },
        ],
    }
}
